### ISSUE TITLE
Conda installations

### ISSUE THREAD

**Issue by sayakgis** [BloodAxe/pytorch-toolbelt#32]
Hello,

Do you have a conda installation, somehow my azure vm and py35 does not load pip installation on jupyter kernels. 

Please suggest.
Sayak

**Comment by BloodAxe** [comment]
Hi! 

No, there is no conda installation for this library and it requires python 3.6: https://github.com/BloodAxe/pytorch-toolbelt/blob/develop/setup.py#L26

**Comment by sarthakpati** [comment]
Hi @BloodAxe, do you mind if I try and put together a conda build recipe?

**Comment by BloodAxe** [comment]
Not sure I'm into it. Why?
The library has pretty loose requirements and it should work on pretty much any environment. I can't think of any benefit in having conda recipe. On the other side it would add maintenance complexity and additional hassle when releasing. For one-man-project I don't think I'd like to have additional burden tbh.

**Comment by sarthakpati** [comment]
The conda package makes combining dependency builds that need compilation much simpler across platforms. Also, the recipe auto-updates when you push a new one to pip, so three is practically no maintenance hassle on your end.
