### ISSUE TITLE
Where is DiceLoss class?

### ISSUE THREAD

**Issue by pokidyshev** [BloodAxe/pytorch-toolbelt#7]

**Comment by Scitator** [comment]
fyi (somehow I was triggered about this issue), we have some [implementation](https://github.com/catalyst-team/catalyst/blob/master/catalyst/contrib/criterion/dice.py)

**Comment by pokidyshev** [comment]
@Scitator Ok, thanks. I was just confused because readme says that there is DiceLoss in this lib.

**Comment by BloodAxe** [comment]
Good catch. Added Dice losses to develop branch. But yes, if the DL framework offers it already - I cannot figure out a reason not to use a out-of-the box loss :)
