### ISSUE TITLE
where is that old attribute JointLoss, what's the name of it now?

### ISSUE THREAD

**Issue by zplu2626** [BloodAxe/pytorch-toolbelt#91]
## To Reproduce

1.
1.
1.

## Environment

 - Pytorch-toolbelt version (e.g., 0.4.4):
 - Pytorch version (e.g., 1.8.1): 
 - Python version (e.g., 3.7):
 - OS (e.g., Linux):
 - Any other relevant information:

**Comment by BloodAxe** [comment]
It was removed in recent release. The reasoning behind this action is the following:
Combining multiple losses in a hard coded way as JointLoss suggested is a wrong design and what you should be doing instead is to leverage some configuration based system to define what losses you want to have, their weights and what input/output keys should go in. 
At the moment of writing, JointLoss looked like a good idea, however after years of building pytorch proficiency it became clear to me that this class is rather a shortcut than a long term solution. So it was dropped.
If you really want to have it I suggest you to copy-paste it's implementation from the past releases.
